<div class="text-center">
    <h1>Contact Me</h1>
</div>

<div class="form-container">
    <form action="/contact" method="POST">
        <div class="form-group">
            <label for="email">Your Email address</label>
            <input type="email" class="form-control" name="email" aria-describedby="email-help" placeholder="Enter email">
            <small id="email-help" class="form-text text-muted">... so I can contact you back, I'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="name">Your Name</label>
            <input type="text" class="form-control" name="name" placeholder="Enter name">              
        </div>
        <div class="form-group">
            <label for="purpose">Purpose</label>
            <select class="form-control" name="purpose">
                <option value="jof">Job Offer (Freelance)</option>
                <option value="jor">Job Offer (Regular)</option>
                <option value="o">Other</option>
            </select>
        </div>
        <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" name="message"></textarea>
        </div>
        
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>