<div class="row ">
    <div class="col-sm text-center">
        <h1>Referrals</h1>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <div class="media">
            <img class="align-self-start mr-3" src="https://randomuser.me/api/portraits/men/18.jpg" alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0">Jacob Terry</h5>
                <p>I observe him goind the extra mile making sure his applications follow the current best practices avaiable for that tech stack. If you need someone who can write testable and maintainable software that can last years, he's the man.</p>
                <p>He really needs to work on his front-end designing skills though as he lacks a lot in that regard.</p>
            </div>
        </div>
    </div>        
    <div class="col-lg">
        <div class="media">
            <img class="align-self-start mr-3" src="https://randomuser.me/api/portraits/men/93.jpg" alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0">Harold Roberts</h5>
                <p>He's our research and development person aside from his job description. He can switch from best practice to quick and dirty for a fast paced environment when trying to create demos for clients.</p>
                <p>I would recommend making use of his broad knowledge, he knows Lotus Notes, .NET, Java, JavaScript, PHP, Python and probably lots more. Just give him his materials (books, training subscriptions).</p>
            </div>
        </div>
    </div>

    <div class="col-lg">
        <div class="media">
            <img class="align-self-start mr-3" src="https://randomuser.me/api/portraits/women/27.jpg" alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0">Beatrice Olson</h5>
                <p>Aside from being an overall reliable developer, he can assist you in managing junior developers. He's produced excellente junior developers that became seniors fast in our short time together.</p>
            </div>
        </div>
    </div>
</div>