<div class="row">
    <div class="col-sm text-center">
        <h1>My Skillset</h1>
        <hr />
    </div>
</div>

<div class="row">
    <div class="col-sm">
        <h3>Full Stack Development</h3>
        <p>
            Experienced full stack developer for web, desktop/standalone, and mobile applications.
        </p>
    </div>
    <div class="col-sm">
        <h3>Architecture & Resource Management</h3>
        <p>
            Experienced in software architecture design and planning, software development project planning and supervision where resources may work in parallel with each other.
        </p>
    </div>
    <div class="col-sm">
        <h3>Task & Time Management</h3>
        <p>
            Had actual field experience as a freelance software developer for 1.5 years before graduating as a computer engineering student, while maintaining academic scholarship.            
        </p>
    </div>
</div>